backend:
  name: github
  repo: keellyp/gabekelly
  accept_roles:
    - admin
  branch: master

publish_mode: editorial_workflow

media_folder: static/img
public_folder: /img

collections:
  - name: "trip"
    label: "Trip"
    folder: "src/pages/trips"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "trip"}
      - {label: "Path", name: "path", default: "{{slug}}"}
      - {label: "Date", name: "date", widget: "date", format: "MMMM YYYY"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Cover", name: "thumbnail", widget: "image"}
      - {label: "Tag", name: "tag", widget: "list"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}